### PR TITLE
adding a good background

### PR DESCRIPTION
**Pull request by ironon**
its essential

### CODE REVIEW

**Comment by ironon** [comment]
if this doesn't get accepted i will eat my cat

**Comment by NoodleBirb** [comment]
i guess you're eating your cat

**Comment by ironon** [comment]
i dont have a cat help

**Comment by ironon** [comment]
what would it take for this to get accepted

**Comment by Jupyner** [comment]
> i guess you're eating your cat

he he he ha

**Comment by ironon** [comment]
> > i guess you're eating your cat
> 
> he he he ha

OMG THANK YOU SO MUCH I DIDN'T WANNA EAT MY CAT

**Pull request merged**
